name: minigest
services:
  webapp:
    container_name: minigest-webapp
    image: ctrlmaniac/minigest:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

  mysqldb:
    container_name: minigest-db
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
