name: minigest
services:
  webapp:
    container_name: minigest-webapp
    image: ctrlmaniac/minigest:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    volumes:
      - ./data/media:/home/media
    env_file:
      - .env

  minigest-postgres:
    container_name: minigest-db
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
