apiVersion: v1
kind: Service
metadata:
  labels:
    app: minigest
  name: minigest
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32000
  selector:
    app: minigest
  type: NodePort
status:
  loadBalancer: {}
